---
- name: Perform Checks to make sure this Playbook will complete successfully
  hosts: localhost
  connection: local
  become: no
  gather_facts: no


  tasks:
    - name: make sure we are running correct Ansible Version
      assert:
        that:
          - ansible_version.major >= 2
          - ansible_version.minor >= 6

    # - name: auto license feature for Ansible Tower
    #   block:
    #     - name: Check that the provided license exists
    #       stat:
    #         path: "{{playbook_dir}}/tower_license.json"
    #       register: stat_result
    #     - debug:
    #         var: stat_result
    #     - fail:
    #         msg: "autolicense is turned on, but we need a license located at {{playbook_dir}}/tower_license.json"
    #       when:
    #        - not stat_result.stat.exists
    #   when:
    #    - autolicense is defined
    #    - autolicense

- name: Deploy Cisco CSR environment in AWS
  hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - manage_ec2_instances
