---
# tasks file for create_webserver

## control node setup ###
- name: set webserver node type
  set_fact:
    ansible_node: "{{ ec2_control_node['ansible'] }}"

- name: find ami for webserver
  ec2_ami_facts:
    region: "{{ ec2_region }}"
    owners: "{{ ec2_instance_types[ansible_node].owners }}"
    filters:
      name: "{{ ec2_instance_types[ansible_node].filter }}"
      architecture: "{{ ec2_instance_types[ansible_node].architecture }}"
  register: amis

- name: save ami for webserver
  set_fact:
    webserver_ami: >
      {{ amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}

- name: Create EC2 instance for webserver
  ec2:
    assign_public_ip: yes
    key_name: "{{ ec2_name_prefix }}-key"
    group: "{{ ec2_webserver_security_group }}"
    instance_type: "{{ ec2_instance_types[ansible_node].size }}"
    image: "{{ webserver_ami.image_id }}"
    region: "{{ ec2_region }}"
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
  register: webserver_output

- name: Ensure tags are present for webserver
  ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{item.1}}"
    state: present
    tags:
      Name: "{{ ec2_name_prefix }}-webserver"
      Demo: "{{ec2_name_prefix}}"
      Function: webserver
  with_indexed_items:
    - "{{ webserver_output.instance_ids }}"
  when: webserver_output.instance_ids is not none
