---
- name: set router node types
  set_fact:
    rtr1_node: "{{ ec2_lab_node_types_networking['rtr1'] }}"
    rtr2_node: "{{ ec2_lab_node_types_networking['rtr2'] }}"

- name: find ami for Cisco CSR 1000v
  ec2_ami_facts:
    region: "{{ ec2_region }}"
    owners: "{{ ec2_instance_types[rtr1_node].owners }}"
    filters:
      name: "{{ ec2_instance_types[rtr1_node].filter }}"
      architecture: "{{ ec2_instance_types[rtr1_node].architecture }}"
  register: amis

- name: save ami for rtr1
  set_fact:
    rtr1_ami: >
      {{ amis.images | selectattr('name', 'defined') | sort(attribute='creation_date') | last }}

- name: Create EC2 instance for rtr1
  ec2:
    assign_public_ip: yes
    key_name: "{{ ec2_name_prefix }}-key"
    group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_instance_types[rtr1_node].size }}"
    image: "{{ rtr1_ami.image_id }}"
    region: "{{ ec2_region }}"
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
  register: rtr1_output

- name: Ensure tags are present for rtr1
  ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{item.1}}"
    state: present
    tags:
      Name: "{{ ec2_name_prefix }}-rtr1"
      Demo: "{{ ec2_name_prefix }}"
      Function: router
  with_indexed_items:
    - "{{ rtr1_output.instance_ids }}"
  when: rtr1_output.instance_ids is not none

- name: Create EC2 instance for rtr2
  ec2:
    assign_public_ip: yes
    key_name: "{{ ec2_name_prefix }}-key"
    group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_instance_types[rtr1_node].size }}"
    image: "{{ rtr1_ami.image_id }}"
    region: "{{ ec2_region }}"
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
  register: rtr2_output

- name: Ensure tags are present for rtr2
  ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{item.1}}"
    state: present
    tags:
      Name: "{{ ec2_name_prefix }}-rtr2"
      Demo: "{{ ec2_name_prefix }}"
      Function: router
  with_indexed_items:
    - "{{ rtr2_output.instance_ids }}"
  when: rtr2_output.instance_ids is not none
